# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Reset NX cache and install dependencies
        run: |
            nx reset
            npm install

      - name: npm install, build, test
        run: |
          npm run build -- --configuration=production --verbose

      - name: Debug Build Output
        run: ls -R ${GITHUB_WORKSPACE}/dist

      - name: Zip artifacts for deployment
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/dist/apps/Sportcaster/ && zip ${GITHUB_WORKSPACE}/sportcaster-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/sportadvies-api/ && zip ${GITHUB_WORKSPACE}/sportadvies-api-release.zip ./* -r

      - name: Upload Sportcaster artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: sportcaster
          path: sportcaster-release.zip

      - name: Upload Sportadvies API artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: sportadvies-api
          path: sportadvies-api-release.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download Sportcaster artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: sportcaster

      - name: Unzip Sportcaster artifact
        run: unzip sportcaster-release.zip

      - name: Deploy to static Azure Web App
        id: deployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_BUSH_0EE755B10 }}
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'dist/apps/Sportcaster'

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download Sportadvies API artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: sportadvies-api

      - name: Unzip Sportadvies API artifact
        run: unzip sportadvies-api-release.zip

      - name: Install dependencies for Sportadvies API
        run: npm install

      - name: Deploy Sportadvies API to Azure Web App
        id: deploysportadviesapi
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sportcaster-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.SPORTADVIESAPI_PUBLISHPROFILE }}
          package: '.'
